"use client";

import { FormEvent, useState } from "react";

type Application = { id: number; eventId: number; status: string; attendanceStatus?: string | null };
const label: Record<string, string> = { registered: "참가가 확정되었습니다.", waitlisted: "정원이 가득 차 대기자로 접수되었습니다.", cancelled: "신청을 취소했습니다." };

export function EventRegistrationForm({ eventId, available, loggedIn, application }: { eventId: number; available: boolean; loggedIn: boolean; application?: Application }) {
  const key = `immanuel-event-cancel-${eventId}`; const [guestSaved, setGuestSaved] = useState<{ application: Application; cancelToken: string } | null>(() => { if (typeof window === "undefined") return null; const saved = window.localStorage.getItem(`immanuel-event-cancel-${eventId}`); if (!saved) return null; try { return JSON.parse(saved) as { application: Application; cancelToken: string }; } catch { window.localStorage.removeItem(`immanuel-event-cancel-${eventId}`); return null; } }); const [open, setOpen] = useState(false); const [notice, setNotice] = useState("");
  const guestApplication = guestSaved?.application ?? null; const cancelToken = guestSaved?.cancelToken ?? "";
  const current = application ?? guestApplication;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setNotice("신청 중입니다…"); const form = new FormData(event.currentTarget); const response = await fetch(`/api/events/${eventId}/registration`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), contact: form.get("contact"), note: form.get("note") }) }); const value = await response.json() as { error?: string; application?: Application; cancelToken?: string }; if (!response.ok || !value.application) { setNotice(value.error ?? "신청하지 못했습니다."); return; } if (value.cancelToken) { const saved = { application: value.application, cancelToken: value.cancelToken }; setGuestSaved(saved); window.localStorage.setItem(key, JSON.stringify(saved)); } setNotice(label[value.application.status] ?? "신청되었습니다."); setOpen(false); }
  async function cancel() { if (!window.confirm("행사 신청을 취소하시겠습니까?")) return; setNotice("취소 중입니다…"); const response = await fetch(`/api/events/${eventId}/registration`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cancelToken }) }); const value = await response.json() as { error?: string }; if (!response.ok) { setNotice(value.error ?? "취소하지 못했습니다."); return; } if (!application) { setGuestSaved({ application: { id: current?.id ?? 0, eventId, status: "cancelled" }, cancelToken: "" }); window.localStorage.removeItem(key); } setNotice("신청을 취소했습니다. 대기자가 있으면 자동으로 참가 확정됩니다."); }
  if (current) return <div className={`event-registration-status status-${current.status}`}><strong>{label[current.status] ?? current.status}</strong>{current.status !== "cancelled" && <button type="button" onClick={cancel}>신청 취소</button>}{notice && <p role="status">{notice}</p>}</div>;
  if (!available) return <p className="event-registration-closed">현재 신청 기간이 아닙니다.</p>;
  return <div className="event-registration"><button className="primary-link" type="button" onClick={() => setOpen((value) => !value)}>{open ? "신청 닫기" : "행사 신청"}</button>{notice && <p role="status">{notice}</p>}{open && <form className="request-form event-registration-form" onSubmit={submit}>{loggedIn ? <p className="event-login-notice">로그인한 회원 정보로 신청합니다. 비멤버로 신청하려면 로그아웃한 뒤 신청해 주세요.</p> : <><label><span>이름</span><input name="name" required minLength={2} maxLength={80} /></label><label><span>연락처</span><input name="contact" inputMode="tel" required placeholder="01012345678" /></label></>}<label><span>전달사항 <small>선택</small></span><textarea name="note" rows={3} maxLength={1000} placeholder="동반 가족, 안내가 필요한 사항 등을 적어 주세요." /></label><button className="primary-link request-submit" type="submit">신청 완료</button></form>}</div>;
}
