"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
export function PasswordResetRequestForm() {
  const [notice, setNotice] = useState(""); const [submitting, setSubmitting] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setNotice(""); const response = await fetch("/api/member/password-reset/request", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const result = (await response.json()) as { error?: string; message?: string; emailConfigured?: boolean }; setNotice(response.ok ? result.emailConfigured === false ? "재설정 기능은 준비됐지만 이메일 발송 연결이 아직 설정되지 않았습니다. 관리자에게 문의해 주세요." : result.message ?? "안내를 보냈습니다." : result.error ?? "요청하지 못했습니다."); setSubmitting(false); }
  return <form className="request-form member-auth-form" onSubmit={submit}><label><span>가입한 이메일</span><input name="email" type="email" autoComplete="email" required /></label><p className="request-form-privacy">가입 여부가 외부에 드러나지 않도록 결과는 동일하게 안내합니다.</p><button className="primary-link request-submit" type="submit" disabled={submitting}>{submitting ? "확인 중…" : "재설정 안내 받기"}</button>{notice && <p className="member-auth-notice" role="status">{notice}</p>}<p className="member-auth-switch"><Link href="/login">로그인으로 돌아가기</Link></p></form>;
}
export function PasswordResetConfirmForm({ token }: { token: string }) {
  const [notice, setNotice] = useState(""); const [done, setDone] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const password = String(data.get("password") ?? ""); if (password !== String(data.get("confirmPassword") ?? "")) { setNotice("비밀번호 확인이 일치하지 않습니다."); return; } const response = await fetch("/api/member/password-reset/confirm", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, password }) }); const result = (await response.json()) as { error?: string }; setNotice(response.ok ? "비밀번호를 변경했습니다. 새 비밀번호로 로그인해 주세요." : result.error ?? "재설정하지 못했습니다."); setDone(response.ok); }
  if (!token) return <div className="request-form member-auth-form"><p className="member-auth-notice">재설정 주소가 올바르지 않습니다.</p><Link className="primary-link" href="/forgot-password">새 주소 요청하기</Link></div>;
  return <form className="request-form member-auth-form" onSubmit={submit}><label><span>새 비밀번호</span><input name="password" type="password" minLength={10} maxLength={128} autoComplete="new-password" required disabled={done} /></label><label><span>새 비밀번호 확인</span><input name="confirmPassword" type="password" minLength={10} maxLength={128} autoComplete="new-password" required disabled={done} /></label><button className="primary-link request-submit" type="submit" disabled={done}>{done ? "변경 완료" : "새 비밀번호 저장"}</button>{notice && <p className="member-auth-notice" role="status">{notice}</p>}{done && <p className="member-auth-switch"><Link href="/login">로그인하기</Link></p>}</form>;
}
