"use client";
import { FormEvent, useEffect, useState } from "react";
type Registration = { id: number; cardType: string; reviewStatus: string; reviewNote: string | null; createdAt: string; address: string; occupation: string; faithStatus: string | null; faithYears: string | null; ordinanceType: string | null; ordinanceChurch: string | null; previousChurchName: string | null };
type FamilyMember = { linkId: number; householdId: number; householdName: string; memberId: number; relationship: string; isPrimary: boolean; memberName: string; memberNumber: string | null };
type Member = { id: number; name: string; email: string; phone: string; birthDate: string; accountStatus: string; membershipStatus: string; role: string; memberNumber: string | null; registrationCategory: number | null; approvedAt: string | null; createdAt: string; address: string | null; occupation: string | null; currentDepartment: string | null; faithYears: string | null; baptismType: string | null; baptismChurch: string | null; previousChurchName: string | null; previousChurchPosition: string | null; serviceHistory: string | null; pastoralNote: string | null; registration: Registration | null; family: FamilyMember[] };
type UnlinkedRegistration = { id: number; requestId: number; cardType: string; reviewStatus: string; createdAt: string; name: string | null; contact: string | null; email: string };
const statusLabels: Record<string, string> = { nonmember: "비멤버", pending: "승인 대기", active: "등록 교인", inactive: "비활성", long_absent: "장기 미출석", transferred: "이명", withdrawn: "탈퇴", deceased: "별세" };
const reviewLabels: Record<string, string> = { received: "접수", reviewing: "검토 중", needs_update: "보완 요청", on_hold: "보류", rejected: "반려", approved: "승인" };

export function MemberManager() {
  const [members, setMembers] = useState<Member[]>([]); const [unlinked, setUnlinked] = useState<UnlinkedRegistration[]>([]); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [query, setQuery] = useState(""); const [statusFilter, setStatusFilter] = useState("all"); const [notice, setNotice] = useState("");
  async function load() { const response = await fetch("/api/admin/members", { cache: "no-store" }); const result = (await response.json()) as { members?: Member[]; unlinkedRegistrations?: UnlinkedRegistration[] }; if (!response.ok) throw new Error(); setMembers(result.members ?? []); setUnlinked(result.unlinkedRegistrations ?? []); setState("ready"); }
  useEffect(() => { fetch("/api/admin/members", { cache: "no-store" }).then(async (response) => { const result = (await response.json()) as { members?: Member[]; unlinkedRegistrations?: UnlinkedRegistration[] }; if (!response.ok) throw new Error(); setMembers(result.members ?? []); setUnlinked(result.unlinkedRegistrations ?? []); setState("ready"); }).catch(() => setState("error")); }, []);
  async function patch(id: number, payload: Record<string, unknown>, success: string) { setNotice("처리 중…"); const response = await fetch("/api/admin/members", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, ...payload }) }); const result = (await response.json()) as { error?: string; member?: { memberNumber?: string } }; setNotice(response.ok ? result.member?.memberNumber ? `${success}: ${result.member.memberNumber}` : success : result.error ?? "처리하지 못했습니다."); if (response.ok) await load(); }
  const keyword = query.trim().toLowerCase(); const filtered = members.filter((item) => (statusFilter === "all" || item.membershipStatus === statusFilter) && (!keyword || [item.name, item.email, item.phone, item.memberNumber, item.currentDepartment].some((value) => value?.toLowerCase().includes(keyword))));
  return <section className="member-manager"><div className="request-inbox-tools"><label><span>회원 검색</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="이름, 전화번호, 이메일, 교인번호, 부서" /></label><label><span>교인 상태</span><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="all">전체</option>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></div>{notice && <p className="content-manager-notice" role="status">{notice}</p>}{unlinked.length > 0 && <UnlinkedCards registrations={unlinked} members={members} patch={patch} />}{state === "loading" && <p className="request-inbox-notice">회원 목록을 불러오는 중입니다…</p>}{state === "error" && <p className="request-inbox-notice is-error">회원 목록을 불러오지 못했습니다.</p>}{state === "ready" && <><p className="member-result-count">검색 결과 {filtered.length}명 · 전체 {members.length}명</p><div className="member-admin-list">{filtered.map((item) => <MemberCard key={item.id} item={item} members={members} patch={patch} />)}</div></>}</section>;
}

function UnlinkedCards({ registrations, members, patch }: { registrations: UnlinkedRegistration[]; members: Member[]; patch: (id: number, payload: Record<string, unknown>, success: string) => Promise<void> }) {
  return <section className="unlinked-registration-panel"><h2>회원계정과 연결되지 않은 새가족 카드</h2><p>비로그인 상태로 제출된 카드입니다. 이름·연락처를 확인한 뒤 정확한 계정과 연결해 주세요.</p>{registrations.map((item) => <form key={item.id} onSubmit={(event) => { event.preventDefault(); const memberId = Number(new FormData(event.currentTarget).get("memberId")); if (memberId && window.confirm(`${item.name ?? "새가족"} 카드를 선택한 회원계정과 연결하시겠습니까?`)) void patch(memberId, { action: "link-registration", registrationId: item.id }, "등록카드를 회원계정과 연결했습니다."); }}><div><strong>{item.name ?? "이름 없음"}</strong><small>{item.contact ?? "연락처 없음"} · {item.email} · {new Date(item.createdAt).toLocaleDateString("ko-KR")}</small></div><select name="memberId" required defaultValue=""><option value="">연결할 회원 선택</option>{members.map((member) => <option value={member.id} key={member.id}>{member.name} · {member.phone}</option>)}</select><button type="submit">계정 연결</button></form>)}</section>;
}

function MemberCard({ item, members, patch }: { item: Member; members: Member[]; patch: (id: number, payload: Record<string, unknown>, success: string) => Promise<void> }) {
  async function saveRegistry(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await patch(item.id, { action: "registry", ...Object.fromEntries(new FormData(event.currentTarget)) }, "교적 정보를 저장했습니다."); }
  async function addFamily(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); if (window.confirm("선택한 교인을 같은 가정으로 연결하시겠습니까?")) await patch(item.id, { action: "family-link", ...data, relatedMemberId: Number(data.relatedMemberId) }, "가족 구성원을 연결했습니다."); }
  function approve(category: number, label: string) { const approvalNote = window.prompt(item.registration ? "승인 메모가 있으면 입력해 주세요. (선택)" : "등록카드가 없습니다. 기존 교인 확인 근거를 입력해 주세요.", "") ?? ""; if (!item.registration && approvalNote.trim().length < 5) return; if (window.confirm(`${item.name}님을 ${label} 교인으로 승인하고 영구 교인번호를 발급하시겠습니까?`)) void patch(item.id, { action: "approve", category, approvalNote }, "교인번호를 발급했습니다"); }
  async function reviewRegistration(reviewStatus: string) { if (!item.registration) return; const needsNote = ["needs_update", "on_hold", "rejected"].includes(reviewStatus); const reviewNote = needsNote ? window.prompt("신청자에게 안내할 사유를 입력해 주세요.", item.registration.reviewNote ?? "") ?? "" : item.registration.reviewNote ?? ""; if (needsNote && reviewNote.trim().length < 3) return; await patch(item.id, { action: "registration-review", registrationId: item.registration.id, reviewStatus, reviewNote }, "등록카드 검토 상태를 변경했습니다."); }
  const linkedIds = new Set(item.family.map((family) => family.memberId));
  return <article className="member-admin-card"><div className="member-admin-heading"><div><small>{statusLabels[item.membershipStatus] ?? item.membershipStatus} · {item.accountStatus === "active" ? "계정 정상" : "계정 정지"}</small><h2>{item.name}</h2></div><strong>{item.memberNumber ?? "교인번호 미발급"}</strong></div><dl><div><dt>연락처</dt><dd>{item.phone}</dd></div><div><dt>이메일</dt><dd>{item.email}</dd></div><div><dt>생년월일</dt><dd>{item.birthDate}</dd></div><div><dt>가입일</dt><dd>{new Date(item.createdAt).toLocaleDateString("ko-KR")}</dd></div></dl>
    <div className={`registration-link-state ${item.registration ? "is-linked" : "is-missing"}`}><strong>{item.registration ? `${item.registration.cardType === "registration" ? "등록카드" : "방문카드"} 연결됨 · ${reviewLabels[item.registration.reviewStatus] ?? item.registration.reviewStatus}` : "연결된 새가족 카드 없음"}</strong>{item.registration && <select value={item.registration.reviewStatus} onChange={(event) => void reviewRegistration(event.target.value)}>{Object.entries(reviewLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select>}</div>
    {!item.memberNumber && <div className="member-approval-actions"><span>교인 등록 승인</span>{[[1, "성인"], [2, "십대"], [3, "십대 이전"]].map(([category, label]) => <button type="button" key={category} onClick={() => approve(Number(category), String(label))}>{label}</button>)}</div>}
    <div className="member-admin-controls"><label><span>교인 상태</span><select value={item.membershipStatus} onChange={(event) => void patch(item.id, { action: "status", status: event.target.value }, "교인 상태를 변경했습니다.")}>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label><span>권한</span><select value={item.role} onChange={(event) => void patch(item.id, { action: "role", role: event.target.value }, "회원 권한을 변경했습니다.")}><option value="member">일반 회원</option><option value="leader">리더</option><option value="staff">사역자</option></select></label><button type="button" onClick={() => void patch(item.id, { action: "account", accountStatus: item.accountStatus === "active" ? "suspended" : "active" }, item.accountStatus === "active" ? "계정을 정지하고 로그인 세션을 종료했습니다." : "계정을 활성화했습니다.")}>{item.accountStatus === "active" ? "계정 정지" : "계정 활성화"}</button></div>
    <details className="member-admin-details"><summary>교적·가족 정보 관리</summary><div className="member-admin-detail-grid"><form className="member-registry-form" onSubmit={saveRegistry}><h3>교적 정보</h3><div className="request-form-grid"><label><span>주소</span><input name="address" defaultValue={item.address ?? item.registration?.address ?? ""} /></label><label><span>직장·하는 일</span><input name="occupation" defaultValue={item.occupation ?? item.registration?.occupation ?? ""} /></label><label><span>현재 부서</span><input name="currentDepartment" defaultValue={item.currentDepartment ?? ""} /></label><label><span>신앙 년수</span><input name="faithYears" defaultValue={item.faithYears ?? item.registration?.faithYears ?? ""} /></label><label><span>세례·침례</span><input name="baptismType" defaultValue={item.baptismType ?? item.registration?.ordinanceType ?? ""} /></label><label><span>집례 교회</span><input name="baptismChurch" defaultValue={item.baptismChurch ?? item.registration?.ordinanceChurch ?? ""} /></label><label><span>이전 교회</span><input name="previousChurchName" defaultValue={item.previousChurchName ?? item.registration?.previousChurchName ?? ""} /></label><label><span>이전 직분</span><input name="previousChurchPosition" defaultValue={item.previousChurchPosition ?? ""} /></label></div><label><span>봉사 이력</span><textarea name="serviceHistory" rows={3} defaultValue={item.serviceHistory ?? ""} /></label><label><span>목회 메모 <small>관리자 전용</small></span><textarea name="pastoralNote" rows={3} defaultValue={item.pastoralNote ?? ""} /></label><button type="submit">교적 저장</button></form>
      <section className="member-family-panel"><h3>가족 구성원</h3>{item.family.length ? <ul>{item.family.map((family) => <li key={family.memberId}><span><strong>{family.memberName}</strong><small>{family.relationship} · {family.memberNumber ?? "번호 미발급"}</small></span>{!family.isPrimary && <button type="button" onClick={() => { if (window.confirm(`${family.memberName}님의 가족 연결을 해제하시겠습니까?`)) void patch(item.id, { action: "family-remove", relatedMemberId: family.memberId }, "가족 연결을 해제했습니다."); }}>연결 해제</button>}</li>)}</ul> : <p>연결된 가족이 없습니다.</p>}<form onSubmit={addFamily}><select name="relatedMemberId" required defaultValue=""><option value="">가족으로 연결할 교인</option>{members.filter((candidate) => candidate.id !== item.id && !linkedIds.has(candidate.id)).map((candidate) => <option value={candidate.id} key={candidate.id}>{candidate.name} · {candidate.phone}</option>)}</select><select name="relationship" defaultValue="배우자">{["배우자", "자녀", "부모", "형제자매", "기타"].map((value) => <option value={value} key={value}>{value}</option>)}</select><button type="submit">가족 연결</button></form></section></div></details>
  </article>;
}
