"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Event = { id: number; title: string; category: string | null; startsAt: string; endsAt: string | null; location: string | null; description: string | null; isPublic: boolean; registrationOpen: boolean; registrationStartsAt: string | null; registrationEndsAt: string | null; capacity: number | null; attendanceEventId: number | null };
type Application = { id: number; eventId: number; memberId: number | null; applicantType: string; applicantName: string; contact: string; status: string; attendanceStatus: string | null; note: string | null; adminNote: string | null; appliedAt: string; memberNumber: string | null };
type Payload = { events: Event[]; applications: Application[] };
const statusLabel: Record<string, string> = { registered: "참가 확정", waitlisted: "대기", cancelled: "취소" };

export function EventManager() {
  const [data, setData] = useState<Payload | null>(null); const [selectedId, setSelectedId] = useState<number | null>(null); const [editingId, setEditingId] = useState<number | null>(null); const [notice, setNotice] = useState("");
  const load = async () => { const response = await fetch("/api/admin/events", { cache: "no-store" }); const value = await response.json() as Payload & { error?: string }; if (!response.ok) { setNotice(value.error ?? "행사 정보를 불러오지 못했습니다."); return; } setData(value); setSelectedId((current) => current ?? value.events[0]?.id ?? null); };
  useEffect(() => { fetch("/api/admin/events", { cache: "no-store" }).then(async (response) => ({ response, value: await response.json() as Payload & { error?: string } })).then(({ response, value }) => { if (!response.ok) { setNotice(value.error ?? "행사 정보를 불러오지 못했습니다."); return; } setData(value); setSelectedId(value.events[0]?.id ?? null); }).catch(() => setNotice("행사 정보를 불러오지 못했습니다.")); }, []);
  const selected = data?.events.find((item) => item.id === selectedId); const applications = useMemo(() => data?.applications.filter((item) => item.eventId === selectedId) ?? [], [data, selectedId]);
  const counts = useMemo(() => applications.reduce<Record<string, number>>((result, item) => ({ ...result, [item.status]: (result[item.status] ?? 0) + 1 }), {}), [applications]);
  async function save(event: FormEvent<HTMLFormElement>, id?: number) { event.preventDefault(); const payload = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/events", { method: id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(id ? { ...payload, id } : payload) }); const result = await response.json() as { error?: string }; if (!response.ok) { setNotice(result.error ?? "저장하지 못했습니다."); return; } setNotice(id ? "행사 설정을 수정했습니다." : "행사를 등록했습니다."); setEditingId(null); event.currentTarget.reset(); await load(); }
  async function action(body: Record<string, unknown>, success: string) { const response = await fetch("/api/admin/events", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { error?: string; status?: string }; setNotice(response.ok ? (result.status === "waitlisted" ? "정원이 가득 차 대기자로 처리했습니다." : success) : result.error ?? "처리하지 못했습니다."); if (response.ok) await load(); }
  async function remove(id: number) { if (!window.confirm("행사와 모든 신청 기록을 삭제하시겠습니까?")) return; const response = await fetch(`/api/events?id=${id}`, { method: "DELETE" }); setNotice(response.ok ? "행사를 삭제했습니다." : "삭제하지 못했습니다."); if (response.ok) { setSelectedId(null); await load(); } }
  if (!data) return <section className="admin-manager"><p>{notice || "행사 정보를 불러오는 중입니다…"}</p></section>;
  return <section className="admin-manager event-manager">{notice && <p className="content-manager-notice" role="status">{notice}</p>}<details className="event-editor" open={!data.events.length}><summary>새 행사 등록</summary><EventForm onSubmit={(event) => save(event)} /></details>
    <div className="admin-toolbar"><label><span>관리할 행사</span><select value={selectedId ?? ""} onChange={(event) => setSelectedId(Number(event.target.value))}><option value="" disabled>행사를 선택하세요</option>{data.events.map((item) => <option value={item.id} key={item.id}>{item.title} · {new Date(item.startsAt).toLocaleDateString("ko-KR")}</option>)}</select></label>{selected && <a className="secondary-admin-action" href={`/api/admin/events?format=csv&eventId=${selected.id}`}>신청자 CSV 다운로드</a>}</div>
    {!selected ? <p className="resource-empty">등록된 행사가 없습니다.</p> : <><section className="event-admin-summary"><article><small>공개 상태</small><strong>{selected.isPublic ? "공개" : "비공개"}</strong></article><article><small>참가 확정</small><strong>{counts.registered ?? 0}{selected.capacity ? ` / ${selected.capacity}` : ""}</strong></article><article><small>대기자</small><strong>{counts.waitlisted ?? 0}</strong></article><article><small>출석 연결</small><strong>{selected.attendanceEventId ? "연결됨" : "미연결"}</strong></article></section>
      <div className="event-admin-actions"><button className="primary-link" type="button" onClick={() => action({ action: "link-attendance", eventId: selected.id }, "행사 출석부를 연결했습니다.")}>{selected.attendanceEventId ? "출석부 연결됨" : "행사 출석부 연결"}</button><button type="button" onClick={() => setEditingId(editingId === selected.id ? null : selected.id)}>{editingId === selected.id ? "수정 닫기" : "행사 설정 수정"}</button><button type="button" onClick={() => remove(selected.id)}>행사 삭제</button></div>
      {editingId === selected.id && <section className="event-edit-panel"><h2>행사 설정</h2><EventForm item={selected} onSubmit={(event) => save(event, selected.id)} /></section>}
      <section className="event-applicant-section"><div><p className="section-kicker">APPLICATIONS</p><h2>신청자와 출석</h2><p>확정자가 취소되면 가장 먼저 신청한 대기자가 자동으로 참가 확정됩니다.</p></div>{!applications.length ? <p className="resource-empty">아직 신청자가 없습니다.</p> : <div className="event-applicant-list">{applications.map((application) => <article key={application.id} className="event-applicant-card"><div><small>{application.applicantType === "member" ? "멤버" : "비멤버"} · {statusLabel[application.status]}</small><h3>{application.applicantName} {application.memberNumber && <span>{application.memberNumber}</span>}</h3><p>{application.contact} · {new Date(application.appliedAt).toLocaleString("ko-KR")}</p>{application.note && <p className="event-application-note">{application.note}</p>}</div><div className="applicant-actions">{application.status !== "registered" && <button className="primary-link" type="button" onClick={() => action({ action: "application-status", id: application.id, status: "registered" }, "참가를 확정했습니다.")}>확정</button>}{application.status !== "waitlisted" && application.status !== "cancelled" && <button type="button" onClick={() => action({ action: "application-status", id: application.id, status: "waitlisted" }, "대기자로 변경했습니다.")}>대기</button>}{application.status !== "cancelled" && <button type="button" onClick={() => action({ action: "application-status", id: application.id, status: "cancelled" }, "신청을 취소했습니다.")}>취소</button>}{application.status === "registered" && <label><span>출석</span><select value={application.attendanceStatus ?? ""} onChange={(event) => { if (event.target.value) void action({ action: "attendance", applicationId: application.id, attendanceStatus: event.target.value }, "출석을 저장했습니다."); }}><option value="">미처리</option><option value="present">출석</option><option value="late">지각</option><option value="excused">사유 결석</option><option value="absent">결석</option></select></label>}</div></article>)}</div>}</section>
    </>}</section>;
}

function EventForm({ item, onSubmit }: { item?: Event; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { const local = (value: string | null | undefined) => value ? value.slice(0, 16) : ""; return <form className="request-form" onSubmit={onSubmit}><label><span>행사명</span><input name="title" required defaultValue={item?.title ?? ""} /></label><label><span>구분 <small>선택</small></span><input name="category" defaultValue={item?.category ?? ""} placeholder="예배, 훈련, 공동체" /></label><div className="request-form-grid"><label><span>시작</span><input name="startsAt" type="datetime-local" required defaultValue={local(item?.startsAt)} /></label><label><span>종료 <small>선택</small></span><input name="endsAt" type="datetime-local" defaultValue={local(item?.endsAt)} /></label></div><label><span>장소 <small>선택</small></span><input name="location" defaultValue={item?.location ?? ""} /></label><label><span>설명 <small>선택</small></span><textarea name="description" rows={4} defaultValue={item?.description ?? ""} /></label><div className="request-form-grid"><label><span>신청 시작 <small>선택</small></span><input name="registrationStartsAt" type="datetime-local" defaultValue={local(item?.registrationStartsAt)} /></label><label><span>신청 마감 <small>선택</small></span><input name="registrationEndsAt" type="datetime-local" defaultValue={local(item?.registrationEndsAt)} /></label></div><label><span>정원 <small>비워두면 제한 없음</small></span><input name="capacity" type="number" min="1" max="100000" defaultValue={item?.capacity ?? ""} /></label><input name="isPublic" type="hidden" value="false" /><label className="request-checkbox"><input name="isPublic" type="checkbox" defaultChecked={item?.isPublic ?? true} /><span>홈페이지에 공개</span></label><input name="registrationOpen" type="hidden" value="false" /><label className="request-checkbox"><input name="registrationOpen" type="checkbox" defaultChecked={item?.registrationOpen ?? false} /><span>홈페이지에서 행사 신청 받기 · 멤버와 비멤버 모두 신청 가능</span></label><button className="primary-link request-submit" type="submit">{item ? "행사 설정 저장" : "행사 등록"}</button></form>; }
